In [9]:
import pandas as pd


In [11]:
import tensorflow as tf

In [12]:
#canstant
con1 = tf.constant(10)
con2 = tf.constant(3.14)
con3 = tf.constant("this is so")
con4 = tf.constant(True)

In [13]:
print(con1, con2, con3, con4)

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(3.14, shape=(), dtype=float32) tf.Tensor(b'this is so', shape=(), dtype=string) tf.Tensor(True, shape=(), dtype=bool)


In [15]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Now you can use tf.Session() as before
sess = tf.Session()



Instructions for updating:
non-resource variables are not supported in the long term


In [62]:
sess.run([con1, con2, con3, con4])

[1, 2, 3, 4]

In [24]:
#operations

Addition = tf.constant(20) + tf.constant(30)
mul = tf.constant(20) * tf.constant(30)

In [25]:
sess.run([Addition, mul])

[50, 600]

In [26]:
Addition = tf.constant([1,2,3,4,5]) + tf.constant([5,4,3,2,1])
mul = tf.constant([1,2,3,4,5]) * tf.constant([5,4,3,2,1])

In [27]:
sess.run([Addition,mul])

[array([6, 6, 6, 6, 6]), array([5, 8, 9, 8, 5])]

In [28]:
str1 = tf.constant("I")
str2 = tf.constant("Love")

In [31]:
sess.run([str1 + str2])

[b'ILove']

In [37]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# Define the placeholder
a = tf.placeholder(tf.int32)

# Define the operation
b = a * 2

In [38]:
sess.run(b,feed_dict={a:[1,2,3,4,5]})

array([ 2,  4,  6,  8, 10])

In [42]:
#sttring placeholder
str_name = tf.placeholder(tf.string)
my_name = "I am" + str_name

In [46]:
sess.run(my_name, feed_dict={str_name:'''Nari'''})

b'I amNari'

In [47]:
#variables 
vae1 = tf.Variable([20],tf.int32)

In [48]:
init = tf.global_variables_initializer()

In [49]:
sess.run(init)

In [50]:
sess.run(vae1)

array([20])

In [53]:
updat_var1 = tf.assign(vae1, [25])

In [54]:
sess.run(updat_var1)

array([25])

In [55]:
#linear model

w = tf.Variable([10], tf.int32)
b = tf.Variable([15], tf.int32)
x=tf.placeholder(tf.int32)

In [56]:
linear_model = w*x + b

In [59]:
init1 = tf.global_variables_initializer()


In [60]:
sess.run(init1)

In [61]:
sess.run(linear_model, feed_dict={x:[1,2,3,4]})

array([25, 35, 45, 55])